
package tracker.util.enums;

public enum Endpoint {

    GET_ALLTASKS,
    GET_TASKS,
    GET_EPICS,
    GET_SUBTASKS,
    GET_HISTORY,
    GET_PRIORITY,
    GET_TASK_ID,
    GET_EPIC_ID,
    GET_SUBTASK_ID,
    GET_EPIC_SUBTASK_LIST,
    DELETE_ALLTASKS,
    DELETE_ALLEPIC,
    DELETE_ALLSUBTASK,
    DELETE_TASK,
    DELETE_EPIC,
    DELETE_SUBTASK,
    POST_TASK,
    POST_EPIC,
    POST_SUBTASK,
    UPDATE_TASK,
    UPDATE_EPIC,
    UPDATE_SUBTASK,
    UNKNOWN,

}